#!/usr/bin/env python3

import cgitb
cgitb.enable()

# echo exact headers and response from given url to this page

URL = "http://tms.affineit.com:4445/SignalAhead/Json/SignalAhead"

from urllib import request

with request.urlopen(URL, []) as response:
    headers = response.info()

    for key in headers:
        print(key + ':', headers[key], end = '\r\n')
    print('', end = '\r\n')

    print(response.read().decode('utf-8'))
