#!/usr/bin/env python3

import cgitb

cgitb.enable()

import os
import psycopg2 as connector
from urllib.parse import urlparse
import json
import sys

DATABASE_URL = os.environ['DATABASE_URL']

dbUrl = urlparse(DATABASE_URL)

DATABASE_OPTIONS = {
    'user': dbUrl.username,
    'password': dbUrl.password,
    'host': dbUrl.hostname,
    'databaseName': dbUrl.path[1:],
    'tableName': 'devicelocations'
}

print('Content-Type: text/html', end='\r\n\r\n')

REQUEST_METHOD = os.environ['REQUEST_METHOD']
CONTENT_TYPE = os.environ['CONTENT_TYPE']
CONTENT_LENGTH = os.environ['CONTENT_LENGTH']

# error cases
if not REQUEST_METHOD == 'POST':
    raise Exception('HTTP method not allowed')

if not 'application/json' in CONTENT_TYPE:
    raise Exception('Incorrect request content type')

if not int(CONTENT_LENGTH) < 1e6:
    raise Exception('Incorrect request content length or content length too large')

# read post data
POST_DATA = sys.stdin.read(int(CONTENT_LENGTH))

content = json.loads(POST_DATA)

print('JSON received. ')

dbConn = connector.connect(user=DATABASE_OPTIONS['user'], password=DATABASE_OPTIONS['password'],
                           host=DATABASE_OPTIONS['host'], database=DATABASE_OPTIONS['databaseName'])

dbCursor = dbConn.cursor()

sqlQueryString = 'SELECT * FROM ' + DATABASE_OPTIONS['tableName'] + ' WHERE trainno = %s;'

dbCursor.execute(sqlQueryString, (content['info']['trainNo'],))

if dbCursor.rowcount > 0:
    if content['status'] == 'active':
        sqlString = 'SELECT * FROM ' + DATABASE_OPTIONS['tableName'] + ' WHERE trainno = %s AND status= %s; '
        dbCursor.execute(sqlString, (content['info']['trainNo'], content['status']))
        if dbCursor.rowcount > 0:
            print('error')
        else:
            # updation
            sqlQueryString1 = 'UPDATE ' + DATABASE_OPTIONS[
                'tableName'] + ' SET trainname = %s, trackname = %s, phone = %s, trainno = %s, latitude = %s, longitude = %s, status= %s WHERE trainno = %s;'
            dbCursor.execute(sqlQueryString1, (content['info']['trainName'], content['info']['trackName'],
                                               content['info']['phone'], content['info']['trainNo'],
                                               content['coordinate']['latitude'],
                                               content['coordinate']['longitude'], content['status'],
                                               content['info']['trainNo']))
    if content['status'] == 'notactive':
        sqlString2 = "SELECT * FROM " + DATABASE_OPTIONS['tableName'] + " WHERE trainno = %s AND status= 'active'; "
        dbCursor.execute(sqlString2, (content['info']['trainNo'],))
        if dbCursor.rowcount > 0:
            # updation
            sqlQueryString1 = 'UPDATE ' + DATABASE_OPTIONS[
                'tableName'] + ' SET trainname = %s, trackname = %s, phone = %s, trainno = %s, latitude = %s, longitude = %s, status= %s WHERE trainno = %s;'
            dbCursor.execute(sqlQueryString1, (content['info']['trainName'], content['info']['trackName'],
                                               content['info']['phone'], content['info']['trainNo'],
                                               content['coordinate']['latitude'],
                                               content['coordinate']['longitude'], content['status'],
                                               content['info']['trainNo']))
else:
    # insertion
    sqlQueryString1 = '''INSERT INTO ''' + DATABASE_OPTIONS['tableName'] + ''' (deviceid, trainname, trackname, phone, trainno, latitude, longitude, status) VALUES (%s, %s, %s, %s, %s, %s, %s, %s);'''
    dbCursor.execute(sqlQueryString1, (content['deviceId'], content['info']['trainName'], content['info']['trackName'],
            content['info']['phone'], content['info']['trainNo'], content['coordinate']['latitude'],
            content['coordinate']['longitude'], content['status']))

dbConn.commit()

dbConn.close()

print('Successfuly got location.')
