#!/usr/bin/env python3

import cgitb

cgitb.enable()

import os
import psycopg2 as connector
from urllib.parse import urlparse
import json
import sys

DATABASE_URL = os.environ['DATABASE_URL']

dbUrl = urlparse(DATABASE_URL)

DATABASE_OPTIONS = {
    'user': dbUrl.username,
    'password': dbUrl.password,
    'host': dbUrl.hostname,
    'databaseName': dbUrl.path[1:],
    'tableName': 'devicelocations'
}

REQUEST_METHOD = os.environ['REQUEST_METHOD']
CONTENT_TYPE = os.environ['CONTENT_TYPE']
CONTENT_LENGTH = os.environ['CONTENT_LENGTH']

# error cases
if not REQUEST_METHOD == 'POST':
    raise Exception('HTTP method not allowed')

if not CONTENT_TYPE == 'application/json':
    raise Exception('Incorrect request content type')

if not int(CONTENT_LENGTH) < 1e6:
    raise Exception('Incorrect request content length or content length too large')

# read post data
POST_DATA = sys.stdin.read(int(CONTENT_LENGTH))

content = json.loads(POST_DATA)

print('Content-Type: text/plain', end='\r\n\r\n')

print('JSON received. ')

dbConn = connector.connect(user=DATABASE_OPTIONS['user'], password=DATABASE_OPTIONS['password'],
                           host=DATABASE_OPTIONS['host'], database=DATABASE_OPTIONS['databaseName'])

dbCursor = dbConn.cursor()

sqlQueryString = '''INSERT INTO ''' + DATABASE_OPTIONS['tableName'] + ''' (deviceid, trainname, trackname, phone, trainno, latitude, longitude) VALUES (%s, %s, %s, %s, %s, %s, %s);'''
            
dbCursor.execute(sqlQueryString, (content['deviceId'], content['info']['trainName'], content['info']['trackName'],
            content['info']['phone'], content['info']['trainNo'], content['coordinate']['latitude'],
            content['coordinate']['longitude']))

dbConn.commit()

dbConn.close()

print('Successfuly got location.')
